{{- if and .Values.imagePullSecrets.create (not .Values.imagePullSecrets.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.imagePullSecrets.name | default "dockerconfigjson" | quote }}
  namespace: {{ .Values.global.namespace }}
  labels:
    app.kubernetes.io/name: {{ include "cinemaabyss.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ required "imagePullSecrets.dockerconfigjson is required when imagePullSecrets.create=true" .Values.imagePullSecrets.dockerconfigjson | quote }}
{{- end }}
